# ref: https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/extras/zipkin.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: istio-system # use this namespace to receive istio information
  labels:
    app: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim:2.23.14
          env:
            - name: STORAGE_METHOD # can be changed to use other db
              value: "mem"